language: php

php:
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --prefer-source

script:
  - phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - php vendor/bin/coveralls -v
