language: php

php:
  - 5.5
  - 5.6

services:
  - mongodb


before_script:
  - composer self-update
  - composer install --prefer-source

script: phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
